on:
  push:
    tags: '*ver.*'

jobs:

  build-deb:
    name: Build deb
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          
      - name: Build with Gradle
        run: ./gradlew packageDeb

      - name: Upload build result
        uses: actions/upload-artifact@v3
        with:
          name: deb
          path: build/compose/binaries/main/deb/ait-businfo_1.0.0-1_amd64.deb

  build-rpm:
    name: Build rpm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          
      - name: Build with Gradle
        run: ./gradlew packageRpm

      - name: Upload build result
        uses: actions/upload-artifact@v3
        with:
          name: rpm
          path: build/compose/binaries/main/rpm/ait-businfo-1.0.0-1.x86_64.rpm

  build-exe:
    name: Build exe
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
    
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          
      - name: Build with Gradle
        run: ./gradlew createDistributable

      - name: Create Zip File - Windows
        run: |
          powershell Compress-Archive -Path build/compose/binaries/main/app/AIT-busInfo -DestinationPath ./AIT-busInfo-Windows.zip
      
      - name: Upload build result
        uses: actions/upload-artifact@v3
        with:
          name: exe
          path: ./AIT-busInfo-Windows.zip

  build-macos:
    name: Build macOS app
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
    
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          
      - name: Build with Gradle
        run: ./gradlew createDistributable
      
      - name: Upload build result
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: build/compose/binaries/main/app/AIT-busInfo.app



  make-release:
    name: make release
    needs: [build-deb, build-rpm, build-exe, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }} 
      
      - name: Download deb data
        uses: actions/download-artifact@v3
        with:
          name: deb

      - name: Download rpm data
        uses: actions/download-artifact@v3
        with:
          name: rpm

      - name: Download exe data
        uses: actions/download-artifact@v3
        with:
          name: exe

      - name: Download app data
        uses: actions/download-artifact@v3
        with:
          name: app

      - name: Upload Release deb
        id: upload_release_asset_deb
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ait-businfo_1.0.0-1_amd64.deb
          asset_name: ait-businfo-linux_amd64.deb
          asset_content_type: application/zip

      - name: Upload Release rpm
        id: upload_release_asset_rpm
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ait-businfo-1.0.0-1.x86_64.rpm
          asset_name: ait-businfo-linux_amd64.rpm
          asset_content_type: application/zip

      - name: Upload Release exe
        id: upload_release_asset_exe
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: AIT-busInfo-Windows.zip
          asset_name: AIT-busInfo-Windows.zip
          asset_content_type: application/zip

      - name: Upload Release app
        id: upload_release_asset_app
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: AIT-busInfo.app
          asset_name: ait-businfo-macos.app
          asset_content_type: application/zip