on:
  push:
    tags: '*ver.*'

jobs:

  build-deb:
    name: Build deb
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          
      - name: Build with Gradle
        run: ./gradlew packageDeb

      - name: Upload build result
        uses: actions/upload-artifact@v3
        with:
          name: deb
          path: build/compose/binaries/main/deb/ait-businfo_1.0.0-1_amd64.deb
      


  build-exe:
    name: Build msi
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
    
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          
      - name: Build with Gradle
        run: ./gradlew packageMsi
      
      - name: Upload build result
        uses: actions/upload-artifact@v3
        with:
          name: msi
          path: build/compose/binaries/main/msi/AIT-busInfo-1.0.0.msi



  make-release:
    name: make release
    needs: [build-deb, build-exe]
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }} 
      
      - name: Download build data
        uses: actions/download-artifact@v3
        with:
          name: deb

      - name: Download build data
        uses: actions/download-artifact@v3
        with:
          name: msi

      - name: Upload Release deb
        id: upload_release_asset_deb
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ait-businfo_1.0.0-1_amd64.deb
          asset_name: ait-businfo.deb
          asset_content_type: application/zip

      - name: Upload Release msi
        id: upload_release_asset_msi
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: AIT-busInfo-1.0.0.msi
          asset_name: ait-businfo.msi
          asset_content_type: application/zip